### ISSUE TITLE
Added PR for chapter 6 - Strings

### ISSUE THREAD

**Issue by theo-armour** [bpesquet/thejsway#8]
Salut @bpesquet 

I added a PR for chapter 8 - Strings

It is worth noting that once you accept these pull requests, the document becomes a multi-author document

I note that you do not have a copyright notice. Legally copyright notices are no longer required - though many authorities advise including one.

https://en.wikipedia.org/wiki/Copyright_notice#Reasons_to_include_an_optional_copyright_notice

May I suggest adding thee words to the LIVENSE page:

copyright &copy; 2017 The JavaScript Way authors

Also in your LICENSE page you include the Creative Commons advisory text before and after the actual license. You might consider deleting the CC comments.
 
Theo

**Comment by bpesquet** [comment]
Salut Theo,

Thanks again for your work. I'm on a business trip so I'll review your PR in the following days.

Regarding legal matters, the [contribution guidelines](https://github.com/bpesquet/thejsway/blob/master/CONTRIBUTING.md) stated that "A merged PR will make you appear in the contributor list. It will, however, be considered a donation of your work to this project". I took example from similar projects such as [Understanding ES6](https://github.com/nzakas/understandinges6#pull-requests) and [YDKJS](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md). 

I have updated this file to make the non-author status of PR creators more explicit. I hope you're ok with that, otherwise let me know.

I also have followed your advice and updated the LICENSE file accordingly.
